---
- name: Install Jenkins
  hosts: jenkins-server
  become: yes
  vars_files:
    - group_vars/all.yml
  
  tasks:
    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes

    - name: Download Jenkins GPG key (ASCII Format)
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /tmp/jenkins.asc
        mode: '0644'

    - name: Convert Jenkins GPG key to binary format
      command: gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg /tmp/jenkins.asc
      args:
        creates: /usr/share/keyrings/jenkins-keyring.gpg

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins
    
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Ensure Jenkins is running
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to initialize
      wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        timeout: 60

    - name: Get Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password_raw

    - name: Show Jenkins initial admin password
      debug:
        msg: "Initial Admin Password: {{ jenkins_password_raw['content'] | b64decode }}"