---
- name: Install MongoDB 8.0 on Ubuntu 24.04
  hosts: mongo_server
  become: yes

  vars:
    mongodb_user: "adminuser"
    mongodb_password: "password123"

  tasks:
    - name: Update apt and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install dependencies
      apt:
        name: [gnupg, curl]
        state: present

    - name: Add MongoDB 8.0 GPG key
      ansible.builtin.shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
        gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg
      args:
        creates: /usr/share/keyrings/mongodb-server-8.0.gpg

    - name: Add MongoDB 8.0 APT source
      copy:
        dest: /etc/apt/sources.list.d/mongodb-org-8.0.list
        content: |
          deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Enable and start mongod
      systemd:
        name: mongod
        enabled: yes
        state: started

    - name: Set bindIp to 0.0.0.0
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:.*'
        line: '  bindIp: 0.0.0.0'
        insertafter: '^net:'

    - name: Enable MongoDB authorization
      blockinfile:
        path: /etc/mongod.conf
        block: |
          security:
            authorization: enabled

    - name: Restart mongod to apply config changes
      systemd:
        name: mongod
        state: restarted

    - name: Verify MongoDB Status
      shell: systemctl status mongod
      register: mongod_status
      changed_when: false

    - name: Show MongoDB Status Output
      debug:
        var: mongod_status.stdout_lines

    - name: Wait for MongoDB to be up
      wait_for:
        host: 127.0.0.1
        port: 27017
        delay: 5
        timeout: 30

    - name: Read mongod.conf from remote
      slurp:
        src: /etc/mongod.conf
      register: mongod_conf_raw

    - name: Decode mongod.conf content
      set_fact:
        mongod_conf_content: "{{ mongod_conf_raw.content | b64decode }}"

    - name: Create MongoDB admin user
      shell: |
        mongosh admin --eval '
        db.createUser({
          user: "{{ mongodb_user }}",
          pwd: "{{ mongodb_password }}",
          roles: [
            { role: "userAdminAnyDatabase", db: "admin" },
            "readWriteAnyDatabase"
          ]
        })'
      args:
        executable: /bin/bash
      when: "'authorization: enabled' in mongod_conf_content"